//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace boots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Payment = new HashSet<Payment>();
        }

        [Key] public int id_Application { get; set; }
        public string Status { get; set; }
        public int FactPrice { get; set; }
        public int id_Client { get; set; }
        public int id_TypeWork { get; set; }
        public int id_Window { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TypeWork TypeWork { get; set; }
        public virtual Window Window { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
