//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace boots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Application = new HashSet<Application>();
        }
    
       [Key] public int id_Client { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string idTelegram { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
