//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boots
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManickEntities3 : DbContext
    {
        private static ManickEntities3 instance;
        public static ManickEntities3 Context()
        {
            if (instance == null)
            {
                instance = new ManickEntities3();
            }
            return instance;
        }
        public ManickEntities3()
            : base("name=ManickEntities3")
        {
        }
   
    
        public DbSet<Application> Application { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Payment> Payment { get; set; }
       
        public DbSet<TypeWork> TypeWork { get; set; }
        public DbSet<Window> Window { get; set; }
    }
}
