//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace boots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
     [Key]   public int id_Payment { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Summ { get; set; }
        public int id_Application { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
