//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace boots
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeWork
    {
        public TypeWork()
        {
            this.Application = new HashSet<Application>();
        }
    
       [Key] public int id_TypeWork { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int BasePrice { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
