//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace boots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Window
    {
        public Window()
        {
            this.Application = new HashSet<Application>();
        }
    
      [Key]  public int id_Window { get; set; }
        public System.DateTime Date { get; set; }
        public string time { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
